version: 2
updates:
  # Root dev dependencies (melos, lints, etc.)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # fl_nodes_core package
  - package-ecosystem: "pub"
    directory: "/packages/fl_nodes_core"
    schedule:
      interval: "weekly"

  # fl_nodes package
  - package-ecosystem: "pub"
    directory: "/packages/fl_nodes"
    schedule:
      interval: "weekly"

  # Example app
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "fl_nodes"
      - dependency-name: "fl_nodes_core"

  # Benchmarks
  - package-ecosystem: "pub"
    directory: "/benchmarks"
    schedule:
      interval: "monthly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
