{
  "sksl": {
    "entrypoint": "grid_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uGridSpacing;\nuniform float uLineWidth;\nuniform vec4 uLineColor;\nuniform float uIntersectionRadius;\nuniform vec4 uIntersectionColor;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec2 FLT_flutter_local_getLineAlpha(vec2 dist, float lineWidth)\n{\n    float halfWidth = lineWidth * 0.5;\n    float pixelRange = 1.0;\n    return vec2(1.0) - smoothstep(vec2(halfWidth - pixelRange), vec2(halfWidth + pixelRange), dist);\n}\n\nfloat FLT_flutter_local_getCircleAlpha(float dist, float radius)\n{\n    float pixelRange = 1.0;\n    return 1.0 - smoothstep(radius - pixelRange, radius + pixelRange, dist);\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 steps = floor((fragCoord / uGridSpacing) + vec2(0.5));\n    vec2 lineCoords = steps * uGridSpacing;\n    vec2 dxdy = abs(fragCoord - lineCoords);\n    vec2 param = dxdy;\n    float param_1 = uLineWidth;\n    vec2 dirAlpha = FLT_flutter_local_getLineAlpha(param, param_1);\n    float dist_1 = distance(fragCoord, lineCoords);\n    float param_2 = dist_1;\n    float param_3 = uIntersectionRadius;\n    float intersectionAlpha = FLT_flutter_local_getCircleAlpha(param_2, param_3);\n    vec4 lineColorWithAlpha = uLineColor * max(dirAlpha.x, dirAlpha.y);\n    vec4 intersectionColorWithAlpha = uIntersectionColor * intersectionAlpha;\n    fragColor = mix(lineColorWithAlpha, intersectionColorWithAlpha, vec4(intersectionAlpha));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uGridSpacing",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uLineWidth",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uLineColor",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uIntersectionRadius",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uIntersectionColor",
        "rows": 4,
        "type": 10
      }
    ]
  }
}