name: benchmarks
description: A sample command-line application.
version: 1.0.0
publish_to: none
license: MIT

resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  fl_nodes_core:
    path: ../packages/fl_nodes_core

  benchmark_harness: ^2.3.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
